Backend/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('venter/', include('Venter.urls')),
    path('', RedirectView.as_view(url='/venter/', permanent=True)),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Venter/urls.py
from django.contrib import auth
from django.urls import path
from django.views.generic import TemplateView

from . import views

urlpatterns = [
    # ex: /venter/
    path('', TemplateView.as_view(template_name='Venter/home.html'), name='home'),
    # ex: /venter/home/
    path('home/', TemplateView.as_view(template_name='Venter/home.html'), name='home'),
    # ex: /venter/logout/
    # path('logout/', views.user_logout, name='logout'),
    path('logout/', auth.views.LogoutView.as_view(template_name="Venter/login.html"), name='logout'),
    # ex: /venter/update_profile/5/
    path('update_profile/<int:pk>', views.UpdateProfileView.as_view(), name='update_profile'),
    # ex: /venter/register_employee/
    path('register_employee/', views.RegisterEmployeeView.as_view(), name='register_employee'),
    # ex: /venter/login/
    path('login/', auth.views.LoginView.as_view(template_name="Venter/login.html"), name='login'),
    # ex: /venter/upload_file/
    path('upload_file/', views.upload_file, name='upload_file'),
    # ex: /venter/delete_file/5/
    path('delete_file/<int:pk>', views.FileDeleteView.as_view(), name='delete_file'),
    # ex: /venter/category_list/civis/
    path('category_list/<organisation_name>', views.CategoryListView.as_view(), name='category_list'),
    # ex: /venter/dashboard/
    path('dashboard/', views.FileListView.as_view(), name='dashboard'),
    # ex: /venter/contact_us/
    path('contact_us/', views.contact_us, name='contact_us'),
    # ex: /venter/search_category/
    # path('search_category/', views.CategorySearchView.as_view(), name='search_category'),
    # ex: /venter/search_file/
    # path('search_file/', views.FileSearchView.as_view(), name='search_file'),
    # ex: /venter/predict_result/5/
    path('predict_result/<int:pk>', views.predict_result, name='predict_result'),
    # ex: /venter/domain_contents/
    path('domain_contents/', views.domain_contents, name='domain_contents'),
    # path('predict/checkOutput/', views.handle_user_selected_data, name='checkOutput'),
    # ex: /venter/download_file/5/
    # path('download_file/<int:pk>', views.file_download, name='download_file'),
]

Venter/models.py
import os
from datetime import date, datetime

from django.contrib.auth.models import User
from django.core.files.storage import default_storage
from django.core.validators import RegexValidator
from django.db import models

from .helpers import get_file_upload_path, get_organisation_logo_path, get_user_profile_picture_path, get_result_file_path


class Organisation(models.Model):
    """
    An organisation that the user belongs to.
    Eg: user_1 belongs to xyz organisation

    # Create an organisation
    >>> organisation_1 = Organisation.objects.create(organisation_name="xyz", organisation_logo="image1.png")
    >>> organisation_2 = Organisation.objects.create(organisation_name="abc", additional_details="Mumbai based company")
    """
    organisation_name = models.CharField(
        max_length=200,
        primary_key=True,
    )
    organisation_logo = models.ImageField(
        upload_to=get_organisation_logo_path,
        null=True,
        blank=True,
        verbose_name="Organisation Logo"
    )
    additional_details = models.TextField(
        blank=True
    )

    def __str__(self):
        return self.organisation_name


class Profile(models.Model):
    """
    A Profile associated with an existing user.
    Eg: organisation name and phone number are some profile details associated with user_1

    # Create a user profile
    >>> prof_1 = Profile.objects.create(user=user_1, organisation_name="abc", profile_picture="image2.png")
    >>> prof_2 = Profile.objects.create(user=user_2, organisation_name="abc", phone_number="9898121212")
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        primary_key=True
    )
    organisation_name = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
        null=True,
    )
    profile_picture = models.ImageField(
        upload_to=get_user_profile_picture_path,
        null=True,
        blank=True,
        default='User Profile Picture/default-avatar.png'
    )
    phone_number = models.CharField(
        blank=True,
        max_length=10,
        validators=[RegexValidator(
            regex=r'^[6-9]\d{9}$', message='Please enter a valid phone number')]
    )
    def __str__(self):
        return self.user.username  # pylint: disable = E1101


class Header(models.Model):
    """
    A Header list associated with each organisation.
    Eg: Organisation xyz may contain headers in the csv file such as- user_id, title etc

    # Create a header instance
    >>> Header.objects.create(organisation_name="xyz", header="user_id")
    """
    organisation_name = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
    )
    header = models.CharField(
        max_length=200
    )

    class Meta:
        verbose_name_plural = 'Headers'


class Category(models.Model):
    """
    A Category list associated with each organisation.
    Eg: Organisation xyz may contain categories in the csv file such as- hawkers, garbage etc

    # Create a category instance
    >>> Category.objects.create(organisation_name="xyz", category="hawkers")
    """
    organisation_name = models.ForeignKey(
        Organisation,
        on_delete=models.CASCADE,
    )
    category = models.CharField(
        max_length=200
    )

    class Meta:
        verbose_name_plural = 'Category'


class File(models.Model):
    """
    A File uploaded by the logged-in user.
    Eg: user_1 may upload a .csv file on 12/12/12

    # Create a file instance
    >>> File.objects.create(uploaded_by=user_1, input_file="file1.csv", uploaded_date = "Jan. 29, 2019, 7:59 p.m.")

    Meta class------
        1) declares a plural name for the 'File' object

    Permissions------
        1) view_organisation_files: Grants permission only to staff members to access 'dashboard_staff.html' template
        2) view_self_files: Grants permission only to authenticated users to access 'dashboard_user.html' template
        2) delete_organisation_files: Grants permission only to staff members to delete files
            uploaded by user(s)/staff member(s) of the organisation
    """
    uploaded_by = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE,
        related_name='file',
    )
    input_file = models.FileField(
        upload_to=get_file_upload_path
    )
    uploaded_date = models.DateTimeField(
        default=datetime.now,
    )
    has_prediction = models.BooleanField(
        default=False,
    )
    output_file_json = models.FileField(blank=True)
    output_file_xlsx = models.FileField(blank=True)

    @property
    def filename(self):
        """
        Returns the name of the csv file uploaded.
        Usage: dashboard_user.html template
        """
        return os.path.basename(self.input_file.name)  # pylint: disable = E1101
    @property
    def output_name(self):
        return os.path.basename(self.output_file.name)

    def delete(self):
        if self.output_file_json:
            default_storage.delete(self.output_file_json)
        if self.output_file_xlsx:
            default_storage.delete(self.output_file_xlsx)
        default_storage.delete(self.input_file)
        print("\n\nInput file should be gone\n\n")
        super().delete()

    class Meta:
        verbose_name_plural = 'File'
        ordering=["-uploaded_date"]

Venter/views.py
import datetime
import json
import operator
import os
from functools import reduce

import jsonpickle
import pandas as pd
from django.conf import settings
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import (LoginRequiredMixin,
                                        PermissionRequiredMixin)
from django.contrib.auth.models import Permission, User
from django.contrib.auth.password_validation import validate_password
from django.core.exceptions import ValidationError
from django.core.mail import mail_admins
from django.db.models import Q
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views import generic
from django.views.decorators.cache import never_cache
from django.views.decorators.http import require_http_methods
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.views.generic.list import ListView

from Backend.settings import MEDIA_ROOT

from Venter.forms import ContactForm, CSVForm, ExcelForm, ProfileForm, UserForm
from Venter.helpers import get_result_file_path
from Venter.models import Category, File, Profile

from .manipulate_csv import EditCsv
from .ML_model.Civis.modeldriver import SimilarityMapping


@login_required
@never_cache
@require_http_methods(["GET", "POST"])
def upload_file(request):
    """
    View logic for uploading CSV file by a logged in user.

    For POST request-------
        1) The POST data, uploaded csv file and a request parameter are being sent to CSVForm as arguments
        2) If form.is_valid() returns true, the user is assigned to the uploaded_by field
        3) file_form is saved and Form instance is initialized again (file_form = CSVForm(request=request)),
           for user to upload another file after successfully uploading the previous file
    For GET request-------
        The file_form is rendered in the template
    """

    if str(request.user.profile.organisation_name) == 'CIVIS':
        excel_form = ExcelForm(request=request)
        if request.method == 'POST':
            excel_form = ExcelForm(
                request.POST, request.FILES, request=request)
            if excel_form.is_valid():
                file_uploaded = excel_form.save(commit=False)
                file_uploaded.uploaded_by = request.user.profile
                file_uploaded.save()
                excel_form = ExcelForm(request=request)
                return render(request, './Venter/upload_file.html', {
                    'file_form': excel_form, 'successful_submit': True})
        return render(request, './Venter/upload_file.html', {
            'file_form': excel_form})
    else:
        file_form = CSVForm(request=request)
        if request.method == 'POST':
            file_form = CSVForm(request.POST, request.FILES, request=request)
            if file_form.is_valid():
                file_uploaded = file_form.save(commit=False)
                file_uploaded.uploaded_by = request.user.profile
                file_uploaded.save()
                file_form = CSVForm(request=request)
                return render(request, './Venter/upload_file.html', {
                    'file_form': file_form, 'successful_submit': True})

        return render(request, './Venter/upload_file.html', {
            'file_form': file_form})


def handle_user_selected_data(request):
    """This function is used to handle the selected categories by the user"""
    if not request.user.is_authenticated:
        # Authentication security check
        return redirect(settings.LOGIN_REDIRECT_URL)
    else:
        rows = request.session['Rows']
        correct_category = []
        company = request.session['company']
        if request.method == 'POST':
            file_name = request.session['filename']
            user_name = request.user.username
            for i in range(rows):
                # We are getting a list of values because the select tag was multiple select
                selected_category = request.POST.getlist(
                    'select_category' + str(i) + '[]')
                if request.POST['other_category' + str(i)]:
                    # To get a better picture of what we are getting try to print "request.POST.['other_category' + str(i)]", request.POST['other_category' + str(i)
                    # others_list=request.POST['other_category' + str(i)]
                    # for element in others_list:
                    #     print(element)
                    #     tuple = (selected_category,element)
                    tuple = (selected_category,
                             request.POST['other_category' + str(i)])
                    # print(request.POST['other_category' + str(i)])
                    # print(tuple)
                    # So here the correct_category will be needing a touple so the data will be like:
                    # [(selected_category1, selected_category2), (other_category1, other_category2)] This will be the output of the multi select
                    correct_category.append(tuple)
                else:
                    # So here the correct_category will be needing a touple so the data will be like:
                    # [(selected_category1, selected_category2)] This will be the output of the multi select
                    correct_category.append(selected_category)
        csv = EditCsv(file_name, user_name, company)
        csv.write_file(correct_category)
        if request.POST['radio'] != "no":
            # If the user want to send the file to Google Drive
            path_folder = request.user.username + "/CSV/output/"
            path_file = 'MEDIA/' + request.user.username + \
                "/CSV/output/" + request.session['filename']
            path_file_diff = 'MEDIA/' + request.user.username + "/CSV/output/Difference of " + request.session[
                'filename']
            upload_to_google_drive.upload_to_drive(path_folder,
                                                   'results of ' +
                                                   request.session['filename'],
                                                   "Difference of " +
                                                   request.session['filename'],
                                                   path_file,
                                                   path_file_diff)
    return redirect("/download")


def handle_uploaded_file(f, username, filename):
    """Just a precautionary step if signals.py doesn't work for any reason."""

    data_directory_root = settings.MEDIA_ROOT
    path = os.path.join(data_directory_root, username,
                        "CSV", "input", filename)
    path_input = os.path.join(data_directory_root, username, "CSV", "input")
    path_output = os.path.join(data_directory_root, username, "CSV", "output")

    if not os.path.exists(path_input):
        os.makedirs(path_input)

    if not os.path.exists(path_output):
        os.makedirs(path_output)

    with open(path, 'wb+') as destination:
        for chunk in f.chunks():
            destination.write(chunk)


class CategoryListView(LoginRequiredMixin, ListView):
    """
    Arguments------
        1) LoginRequiredMixin: Request to update profile details by non-authenticated users,
        will throw an HTTP 404 error
        2) ListView: View to display the category list for the organisation to which the logged-in user belongs

    Functions------
        1) get_queryset(): Returns a new QuerySet filtering categories
        based on the organisation name passed in the parameter.
    """
    model = Category
    paginate_by = 10

    def get_queryset(self):

        result = Category.objects.filter(organisation_name=self.request.user.profile.organisation_name)

        query = self.request.GET.get('q','')

        if query:
            result = Category.objects.filter(category__icontains=query)

        return result


class UpdateProfileView(LoginRequiredMixin, UpdateView):
    """
    Arguments------
        1) UpdateView: View to update the user profile details for the logged-in user
        2) LoginRequiredMixin: Request to update profile details by non-authenticated users,
        will throw an HTTP 404 error
    """
    model = Profile
    success_url = reverse_lazy('home')

    def post(self, request, *args, **kwargs):
        profile_form = ProfileForm(
            request.POST, request.FILES, instance=request.user.profile)
        if profile_form.is_valid():
            profile_form.save()
            profile_form = ProfileForm(instance=request.user.profile)
            return render(request, './Venter/update_profile.html',
                          {'profile_form': profile_form, 'successful_submit': True})
        else:
            return render(request, './Venter/update_profile.html',
                          {'profile_form': profile_form})

    def get(self, request, *args, **kwargs):
        profile_form = ProfileForm(instance=request.user.profile)
        return render(request, './Venter/update_profile.html', {'profile_form': profile_form})


class RegisterEmployeeView(LoginRequiredMixin, CreateView):
    """
    Arguments------
        1) CreateView: View to register a new user(employee) of an organisation.
    Note------
        1) The organisation name for a newly registered employee is taken from
           the profile information of the staff member registering the employee.
        2) The profile.save() returns an instance of Profile that has been saved to the database.
            This occurs only after the profile is created for a new user with the 'profile.user = user'
        3) The validate_password() is an in-built password validator in Django
            # module-django.contrib.auth.password_validation
        Ref: https://docs.djangoproject.com/en/2.1/topics/auth/passwords/
        4) The user_form instance is initialized again (user_form = UserForm()), for staff member

Venter/templates/Venter/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <!--Loads the path to your static files-->
    {% load staticfiles %}
    <meta charset="utf-8" />
    <title>{% block title %}{% endblock %}</title>
    <link rel="apple-touch-icon" sizes="76x76" href="../../static/assets/img/apple-icon.png">
    <link rel="icon" type="image/png" href="../../static/assets/img/favicon.ico">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0, shrink-to-fit=no'
        name='viewport' />
    <!--     Fonts and icons     -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700,200" rel="stylesheet" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <!-- LINEARICONS -->
    <link rel="stylesheet" href="../../static/assets/fonts/linearicons/style.css">
    <!-- CSS Files -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}" />
    <link href="../../static/assets/css/bootstrap.min.css" rel="stylesheet" />
    <link href="../../static/assets/css/light-bootstrap-dashboard.css?v=2.0.1" rel="stylesheet" />

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

</head>

<body>
    <!---lightboard template-->
    <div class="wrapper">
        {% if user.is_authenticated %}
        <script>
            console.log("----")
            console.log('{{user.profile.organisation_name}}')
        </script>
            <!--Side Nav Bar--->
        <div class="sidebar" data-image="../../static/assets/img/sidebar-5.jpg" data-color="blue">
                <div class="sidebar-wrapper">
                    <div class="logo-nav">
                        <a href="{% url 'home' %}" class="simple-text">
                            <img src="../../static/assets/img/logo_3.png" alt="logo" class="imagelogo-base">
                        </a>
                    </div>

                    <ul class="nav navbar-nav">

                        <li class="dashboard-item">
                            <a class="nav-link" href="{% url 'dashboard' %}">
                                <i class="nc-icon nc-grid-45"></i>
                                <p>Dashboard</p>
                            </a>
                        </li>
                        {% if user.is_staff %}
                        <li class="register-employee-item">
                            <a class="nav-link" href="{% url 'register_employee' %}">
                                <i class="nc-icon nc-notes"></i>
                                <p>Register Employee</p>
                            </a>
                        </li>
                        {% endif %}

                        <li class="upload-file-item">
                            <a class="nav-link" href="{% url 'upload_file' %}">
                                <i class="nc-icon nc-simple-add"></i>
                                <p>Upload File</p>
                            </a>
                        </li>

                        <li class="user-profile-item">
                            <a class="nav-link" href="{% url 'update_profile' request.user.pk %}">
                                <i class="nc-icon nc-circle-09"></i>
                                <p>User Profile</p>
                            </a>
                        </li>

                        <!-- {% if request.user.profile.organisation_name != "CIVIS" %}
                        <li class="category-list-item">
                            <a class="nav-link" href="{% url 'category_list' request.user %}">
                                <i class="nc-icon nc-bullet-list-67"></i>
                                <p>Category List</p>
                            </a>
                        </li>
                        {% endif %} -->

                        <li class="nav-item active active-pro">
                            <a class="nav-link active" href="{% url 'logout' %}">
                                <i class="nc-icon nc-button-power"></i>
                                <p>Log out</p>
                            </a>
                        </li>
                    </ul>
                </div>
        </div>
        <div class="main-panel">
            {% block content %}
            {% endblock %}                
        </div>
        {% endif %}
    </div>
</body>
<!--   Core JS Files   -->
<script src="../../static/assets/js/core/jquery.3.2.1.min.js" type="text/javascript"></script>
<script src="../../static/assets/js/core/popper.min.js" type="text/javascript"></script>
<script src="../../static/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
<!--  Plugin for Switches, full documentation here: http://www.jque.re/plugins/version3/bootstrap.switch/ -->
<script src="../../static/assets/js/plugins/bootstrap-switch.js"></script>
<!--  Chartist Plugin  -->
<script src="../../static/assets/js/plugins/chartist.min.js"></script>
<!--  Notifications Plugin    -->
<script src="../../static/assets/js/plugins/bootstrap-notify.js"></script>
<!-- Control Center for Light Bootstrap Dashboard: scripts for the example pages etc -->
<script src="../../static/assets/js/light-bootstrap-dashboard.js?v=2.0.1" type="text/javascript"></script>

</html>

Venter/templates/Venter/category_list.html
{% extends 'Venter/base.html' %}
{% block title %}Category List{% endblock %}
{% block content %}

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="../../static/assets/css/category_list.css">


<div class="outer-category">
  <div class="container-category">
    {% if category_list %}
    <div class="search-form-category">
      <form action="{% url 'category_list' %}" method="get">
        <div class="form-group row">
            <div class="col-lg-3">
              <input type="submit" value="Search" class="btn btn-primary active">
            </div>
            <div class="col-lg-7">
              <input type="text" name="q" class="form-control" placeholder="Search category">
            </div>
        </div>
      </form>
    </div><br>

    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Category List</th>
        </tr>
      </thead>
      <tbody>
        {% for c in category_list %}
        <tr>
          <td>
            {{c.category}}
          <td>
        </tr>
        {% endfor %}
      </tbody>
    </table>

    <div class="div-pagination">
      {% block pagination %}
      {% if is_paginated %}
      <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item">
          <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
        </li>
        {% else %}
        <li class="page-item" disabled="">
          <a class="page-link">Previous</a>
        </li>
        {% endif %}

        {% for i in paginator.page_range %}
        {% if page_obj.number == i %}
        <li class="page-item active">
          <a class="page-link"> <span>{{ i }} <span class="sr-only">(current)</span></span></a>
        </li>
        {% else %}
        <li class="page-item">
          <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
        </li>
        {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
        <li class="page-item">
          <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
        </li>
        {% else %}
        <li class="page-item" disabled="">
          <a class="page-link">Next</a>
        </li>
        {% endif %}
      </ul>
      {% endif %}
      {% endblock %}
    </div>

    {% else %}
    <h3>No category list available. Please contact the administrator</h3>
    {% endif %}
  </div>
</div>

{% endblock %}

Venter/templates/Venter/dashboard.html
{% extends 'Venter/base.html' %}
{% block title %}Dashboard{% endblock %}
{% block content %}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="../../static/assets/css/dashboard.css">



  {% if file_list %}
  <div class="inner-db-file">
    <div class="row">
      <div class="col-sm-9">
        <form action="{% url 'dashboard' %}" method="get">
            <div class="form-group row">
                <div class="col-sm-1">
                  <input type="submit" value="Search" class="btn btn-primary active">
                </div>&nbsp;&nbsp;
                <div class="col-sm-9">
                    <input type="text" name="q" class="form-control" placeholder="Search file">
                </div>
            </div>
        </form>
      </div>
      <div class="col-sm-1">
        <a href="{% url 'upload_file' %}">
          <button type="button" class="btn btn-primary upload-button">
            Upload File &nbsp;<i class="fa fa-plus plus-fa" aria-hidden="true"></i>
          </button>
        </a>
      </div>
    </div><br>

    <table class="table table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Input File</th>
          <th>Uploaded By</th>
          <th>Upload Date</th>
          <th>Upload Time</th>
          <th>Prediction results</th>
          <th>Download Results</th>
          {% if user.is_staff %}
          <th>Delete</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for file in file_list %}
        <tr>
          <td>{{ file.filename }}</td>
          <td>{{ file.uploaded_by  }}</td>
          <td>{{ file.uploaded_date.date }}</td>
          <td>{{ file.uploaded_date.astimezone.time }}</td>
          <td>
            <a href="{% url 'predict_result' file.pk %}">
              <button class="btn btn-success predict-button">Categorize</button>
            </a>
          </td>
          <td>
            <a href="{{file.output_file_xlsx}}", download="results.xlsx">
              <i class="fa fa-download download-fa" aria-hidden="true"></i>
            </a>
          </td>
            {% if user.is_staff == True %}
            <td>
              <a href="{% url 'delete_file' file.pk %}">
                  <i class="fa fa-trash-o trash-fa" aria-hidden="true"></i>
              </a>
            </td>
            {% endif %}
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>


    <div class="div-pagination">
        {% block pagination %}
        {% if is_paginated %}
        <ul class="pagination justify-content-center">
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.previous_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Previous</a>
          </li>
          {% else %}
          <li class="page-item" disabled="">
            <a class="page-link">Previous</a>
          </li>
          {% endif %}

          {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
          <li class="page-item active">
            <a class="page-link"> <span>{{ i }} <span class="sr-only">(current)</span></span></a>
          </li>
          {% else %}
          <li class="page-item">
            <a class="page-link" href="?page={{ i }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">{{ i }}</a>
          </li>
          {% endif %}
          {% endfor %}

          {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="{{ request.path }}?page={{ page_obj.next_page_number }}{% if request.GET.q %}&q={{ request.GET.q }}{% endif %}">Next</a>
          </li>
          {% else %}
          <li class="page-item" disabled="">
            <a class="page-link">Next</a>
          </li>
          {% endif %}
        </ul>
        {% endif %}
        {% endblock %}
      </div>
  </div>
  {% else %}
  <div class="inner-db-no-file">
    <div class="uploadtext">Upload File</div>
    <div class="file-upload">
      <a href="{% url 'upload_file' %}">
        <i class="fa fa-arrow-up"></i>
      </a>
    </div>
  </div>
  {% endif %}




{% endblock %}